Remove qhack banner - DO NOT MERGE UNTIL WEDNESDAY MARCH 1ST
PennyLaneAI/pennylane.ai pull request #72
Opened 2023-02-24 16:00 UTC by doctorperceptron

2023-02-24 16:04 UTC, Anakhom approved these changes
You beat me to it :joy:
LGTM, thank you!

2023-02-24 17:01 UTC, josh146 requested changes
Hey @doctorperceptron, something odd has happened in the PR preview 🤔 

![image](https://user-images.githubusercontent.com/2959003/221241157-09eaedd6-4ad8-4c84-baa9-ec78817b86b7.png)

Everything is 100% width

2023-02-24 17:29 UTC, Anakhom requested changes
Good catch @josh146 ! I think this suggestion ought to fix it.

2023-02-24 17:29 UTC, Anakhom commented on jinja/index.html
> +        <div class="pt-5 text-center teal-text text-lighten-2"></div>
```suggestion
        <div class="pt-5 text-center teal-text text-lighten-2">
            <img src="img/pennylane_stacked.png" class="logo" srcset="img/pennylane_logo.svg"/>
        </div>
```

2023-02-24 17:29 UTC, Anakhom commented on jinja/index.html
>          </div>
```suggestion

```

2023-02-24 18:20 UTC, doctorperceptron commented
Thank you! All fixed

![image](https://user-images.githubusercontent.com/50180049/221258900-691fa27d-20be-4c87-91da-182bb60e0009.png)

2023-02-24 23:01 UTC, josh146 approved these changes
Thanks @doctorperceptron!

2023-02-27 14:06 UTC, AndrewGardhouse approved these changes
🚀

2023-02-27 15:38 UTC, Anakhom approved these changes

2023-03-01 20:36 UTC, merged