[WIP] Adds a news ticker.
PennyLaneAI/pennylane.ai pull request #8
Opened 2020-12-13 14:42 UTC by glassnotes

Adds a simple news ticker to the top of the main page that can showcase things like recent releases, news, new demos, etc.

2020-12-19 15:24 UTC, josh146 requested changes
This is awesome @glassnotes! It will be great to have on the landing page.

While it looks really nice in desktop mode, I noticed two issues in mobile mode:

* Long news items 'wrap around', with additional lines resulting in a separate ticker item. E.g., for the QHACK one, the 2021 wraps over to a new line, and in terms of the animation acts like a separate news item. This is probably minor though.

* Maybe we should hide the 'Latest news' title from mobile view:
  ![image](https://user-images.githubusercontent.com/2959003/102692868-5b829200-4251-11eb-8b9d-45f26cffd4a5.png)

2020-12-19 15:24 UTC, josh146 commented on jinja/index.html
> +                variational quantum programming framework</a>.
Should we change this wording to be the same as the title of the PR?

2020-12-21 21:29 UTC, glassnotes commented
> Long news items 'wrap around', with additional lines resulting in a separate ticker item. E.g., for the QHACK one, the 2021  wraps over to a new line, and in terms of the animation acts like a separate news item. This is probably minor though.

I was able to partially fix this by turning off the word wrap - however this means that part of the items is cut off on small screens. What would be really cool is to make it so that items scroll horizontally if they are too long, but I think that would be complicated as it would affect the rate vertical scrolling (like it would have to wait for horizontal scrolling to finish first). @josh146 do you have any experience with that kind of thing?

>  Maybe we should hide the 'Latest news' title from mobile view:
>  ![image](https://user-images.githubusercontent.com/2959003/102692868-5b829200-4251-11eb-8b9d-45f26cffd4a5.png)

This is fixed!

2020-12-22 07:27 UTC, josh146 commented
> What would be really cool is to make it so that items scroll horizontally if they are too long, but I think that would be complicated as it would affect the rate vertical scrolling (like it would have to wait for horizontal scrolling to finish first). @josh146 do you have any experience with that kind of thing?

Unfortunately I don't! The CSS/JS trickery here is already beyond what I've done before 😆 

In retrospect, maybe the word wrap is the best approach? I think in this particular example it looked a bit weird (because the line just had `2021!`), but in general the wrapped line might be longer so it will look more natural.

> This is fixed!

💪

2021-04-15 07:03 UTC, josh146 commented
@glassnotes just revisiting this PR (apologies if I let it slip!)

I was wondering if we could 'automate' the ticker to show the three most recent blog posts + summaries?

Perhaps we could even go further, and have a section on the page for the three latest posts?

2021-04-15 14:28 UTC, glassnotes commented
@josh146 I forgot about this! 

The issue with it was that I was not able to get it looking nice for variable screen sizes, as well as word wrapping for long titles. (I imagine these are solved problems, I just don't know how to implement it). 

I like the idea of having a section on the page for recent posts; are you thinking kind of like the "featured demos" carousel on the main demo page?

2021-04-15 14:29 UTC, josh146 commented
> I like the idea of having a section on the page for recent posts; are you thinking kind of like the "featured demos" carousel on the main demo page?

Yep, but somehow automatically updated by grabbing the blog RSS feed (so that we don't constantly have to update it ourselves!)

2021-04-15 17:06 UTC, co9olguy commented
> > I like the idea of having a section on the page for recent posts; are you thinking kind of like the "featured demos" carousel on the main demo page?
> 
> Yep, but somehow automatically updated by grabbing the blog RSS feed (so that we don't constantly have to update it ourselves!)

Perhaps as a github action that is run whenever a new PR is merged on the `blog` repo?

2021-04-15 17:09 UTC, josh146 commented
> Perhaps as a github action that is run whenever a new PR is merged on the blog repo?

I was thinking actually more along the lines of javascript within the landing page, that dynamically fetches and displays the blog content.

One advantage over the github action approach is that it wouldn't require new deploys of the landing page to update it.

2021-05-12 12:30 UTC, josh146 commented
Update: we could use `jquery.rss` to load the blog RSS and display it on the homepage:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>jquery.rss example</title>

    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css"
      rel="stylesheet"
    />

    <script src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-rss/3.3.0/jquery.rss.min.js"></script>

    <script>
      jQuery(function ($) {
        $('#rss-feeds').rss('http://pennylane.ai/blog/feeds/rss.xml', {
          entryTemplate:
            '<a href="{url}"><div class="card mb-4"><div class="card-body"><div class="card-title">{date} -- {title}</div>{teaserImage}{shortBodyPlain}...</div></div>',
          layoutTemplate: "<div class='feed-container'>{entries}</div>",
          limit: 3,
          support: false,
        });
      });
    </script>
  </head>

  <body>
    <div class="container">
      <div class="card-group" id="rss-feeds" style="display: flex"></div>
    </div>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/2959003/117975011-ce0b2000-b360-11eb-98e5-550f7cbbd87f.png)

2021-05-12 12:43 UTC, co9olguy commented
Yeah, that'd be a nice idea :slightly_smiling_face:

2021-06-18 21:22 UTC, glassnotes commented
Closing this now that #20 has been merged :tada:

2021-06-18 21:22 UTC, closed without merging